version: '3.8'
services:
  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - "9000:9000"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

  bot:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - whisper-asr
      - qdrant
    restart: unless-stopped
